services:
  - type: web
    name: ai-mobile-shopping-agent-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CSE_ID
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: SETUP_DB
        value: "true"

  - type: pserv
    name: ai-mobile-shopping-agent-db
    env: postgresql
    plan: free
    databaseName: mobile_shop_db
    databaseUser: postgres
