from database import SessionLocal, MobilePhone

def seed_database():
    """Seed the database with sample mobile phone data"""
    db = SessionLocal()
    
    # Sample mobile phone data
    phones_data = [
        {
            "name": "iPhone 15 Pro",
            "brand": "Apple",
            "price": 134900,
            "display_size": 6.1,
            "display_resolution": "2556 x 1179",
            "processor": "A17 Pro",
            "ram": 8,
            "storage": 128,
            "camera_main": "48MP + 12MP + 12MP",
            "camera_front": "12MP",
            "battery_capacity": 3274,
            "charging_speed": "20W",
            "os": "iOS 17",
            "weight": 187,
            "dimensions": "146.6 x 70.6 x 8.25 mm",
            "colors": "Natural Titanium, Blue Titanium, White Titanium, Black Titanium",
            "features": "Face ID, MagSafe, USB-C, Action Button",
            "image_url": "https://example.com/iphone15pro.jpg",
            "description": "Latest iPhone with titanium design and A17 Pro chip",
            "ois": True,
            "eis": True,
            "wireless_charging": True,
            "water_resistance": "IP68",
            "fingerprint_sensor": False,
            "face_unlock": True
        },
        {
            "name": "Samsung Galaxy S24 Ultra",
            "brand": "Samsung",
            "price": 124999,
            "display_size": 6.8,
            "display_resolution": "3120 x 1440",
            "processor": "Snapdragon 8 Gen 3",
            "ram": 12,
            "storage": 256,
            "camera_main": "200MP + 50MP + 10MP + 10MP",
            "camera_front": "12MP",
            "battery_capacity": 5000,
            "charging_speed": "45W",
            "os": "Android 14",
            "weight": 232,
            "dimensions": "162.3 x 79.0 x 8.6 mm",
            "colors": "Titanium Black, Titanium Gray, Titanium Violet, Titanium Yellow",
            "features": "S Pen, AI features, 7 years updates",
            "image_url": "https://example.com/s24ultra.jpg",
            "description": "Premium Android flagship with S Pen and AI capabilities",
            "ois": True,
            "eis": True,
            "wireless_charging": True,
            "water_resistance": "IP68",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "OnePlus 12",
            "brand": "OnePlus",
            "price": 64999,
            "display_size": 6.82,
            "display_resolution": "3168 x 1440",
            "processor": "Snapdragon 8 Gen 3",
            "ram": 12,
            "storage": 256,
            "camera_main": "50MP + 64MP + 48MP",
            "camera_front": "32MP",
            "battery_capacity": 5400,
            "charging_speed": "100W",
            "os": "OxygenOS 14",
            "weight": 220,
            "dimensions": "164.3 x 75.8 x 9.15 mm",
            "colors": "Silky Black, Flowy Emerald",
            "features": "Alert Slider, Fast charging, Gaming mode",
            "image_url": "https://example.com/oneplus12.jpg",
            "description": "Flagship killer with fast charging and premium features",
            "ois": True,
            "eis": True,
            "wireless_charging": True,
            "water_resistance": "IP65",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "Google Pixel 8 Pro",
            "brand": "Google",
            "price": 106999,
            "display_size": 6.7,
            "display_resolution": "3120 x 1440",
            "processor": "Google Tensor G3",
            "ram": 12,
            "storage": 128,
            "camera_main": "50MP + 48MP + 48MP",
            "camera_front": "10.5MP",
            "battery_capacity": 5050,
            "charging_speed": "30W",
            "os": "Android 14",
            "weight": 213,
            "dimensions": "162.6 x 76.5 x 8.8 mm",
            "colors": "Obsidian, Porcelain, Bay",
            "features": "AI features, Magic Eraser, Call Screen",
            "image_url": "https://example.com/pixel8pro.jpg",
            "description": "AI-powered camera phone with Google's best features",
            "ois": True,
            "eis": True,
            "wireless_charging": True,
            "water_resistance": "IP68",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "Xiaomi 14 Ultra",
            "brand": "Xiaomi",
            "price": 99999,
            "display_size": 6.73,
            "display_resolution": "3200 x 1440",
            "processor": "Snapdragon 8 Gen 3",
            "ram": 16,
            "storage": 512,
            "camera_main": "50MP + 50MP + 50MP + 50MP",
            "camera_front": "32MP",
            "battery_capacity": 5300,
            "charging_speed": "90W",
            "os": "MIUI 15",
            "weight": 224,
            "dimensions": "161.4 x 75.3 x 9.2 mm",
            "colors": "Black, White",
            "features": "Leica camera system, Fast charging",
            "image_url": "https://example.com/xiaomi14ultra.jpg",
            "description": "Photography-focused flagship with Leica partnership",
            "ois": True,
            "eis": True,
            "wireless_charging": True,
            "water_resistance": "IP68",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "Samsung Galaxy A55 5G",
            "brand": "Samsung",
            "price": 39999,
            "display_size": 6.6,
            "display_resolution": "2340 x 1080",
            "processor": "Exynos 1480",
            "ram": 8,
            "storage": 128,
            "camera_main": "50MP + 12MP + 5MP",
            "camera_front": "32MP",
            "battery_capacity": 5000,
            "charging_speed": "25W",
            "os": "Android 14",
            "weight": 213,
            "dimensions": "161.1 x 77.4 x 8.2 mm",
            "colors": "Awesome Iceblue, Awesome Lilac, Awesome Navy",
            "features": "5G, Samsung Knox, 4 years updates",
            "image_url": "https://example.com/a55.jpg",
            "description": "Mid-range 5G phone with premium build quality",
            "ois": True,
            "eis": True,
            "wireless_charging": False,
            "water_resistance": "IP67",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "OnePlus 12R",
            "brand": "OnePlus",
            "price": 39999,
            "display_size": 6.78,
            "display_resolution": "2780 x 1264",
            "processor": "Snapdragon 8 Gen 2",
            "ram": 8,
            "storage": 128,
            "camera_main": "50MP + 8MP + 2MP",
            "camera_front": "16MP",
            "battery_capacity": 5500,
            "charging_speed": "100W",
            "os": "OxygenOS 14",
            "weight": 207,
            "dimensions": "163.3 x 75.3 x 8.8 mm",
            "colors": "Iron Gray, Cool Blue",
            "features": "Alert Slider, Fast charging, Gaming performance",
            "image_url": "https://example.com/oneplus12r.jpg",
            "description": "Performance-focused phone with flagship features at mid-range price",
            "ois": True,
            "eis": True,
            "wireless_charging": False,
            "water_resistance": "IP64",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "Google Pixel 8a",
            "brand": "Google",
            "price": 52999,
            "display_size": 6.1,
            "display_resolution": "2400 x 1080",
            "processor": "Google Tensor G3",
            "ram": 8,
            "storage": 128,
            "camera_main": "64MP + 13MP",
            "camera_front": "13MP",
            "battery_capacity": 4492,
            "charging_speed": "18W",
            "os": "Android 14",
            "weight": 193,
            "dimensions": "152.1 x 72.7 x 8.9 mm",
            "colors": "Obsidian, Porcelain, Bay, Aloe",
            "features": "AI features, Magic Eraser, 7 years updates",
            "image_url": "https://example.com/pixel8a.jpg",
            "description": "Affordable Pixel with flagship AI features",
            "ois": True,
            "eis": True,
            "wireless_charging": True,
            "water_resistance": "IP67",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "Realme GT 6",
            "brand": "Realme",
            "price": 35999,
            "display_size": 6.78,
            "display_resolution": "2780 x 1264",
            "processor": "Snapdragon 8s Gen 3",
            "ram": 12,
            "storage": 256,
            "camera_main": "50MP + 8MP + 2MP",
            "camera_front": "32MP",
            "battery_capacity": 5500,
            "charging_speed": "120W",
            "os": "Realme UI 5.0",
            "weight": 199,
            "dimensions": "162.9 x 75.1 x 8.6 mm",
            "colors": "Fluid Silver, Razor Green",
            "features": "Gaming mode, Fast charging, AI features",
            "image_url": "https://example.com/realmeGT6.jpg",
            "description": "Gaming-focused phone with flagship performance",
            "ois": True,
            "eis": True,
            "wireless_charging": False,
            "water_resistance": "IP65",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "Vivo X100 Pro",
            "brand": "Vivo",
            "price": 89999,
            "display_size": 6.78,
            "display_resolution": "2800 x 1260",
            "processor": "MediaTek Dimensity 9300",
            "ram": 16,
            "storage": 512,
            "camera_main": "50MP + 50MP + 64MP",
            "camera_front": "32MP",
            "battery_capacity": 5400,
            "charging_speed": "100W",
            "os": "Funtouch OS 14",
            "weight": 225,
            "dimensions": "164.1 x 75.3 x 9.1 mm",
            "colors": "Starry Blue, Sunset Orange",
            "features": "Zeiss optics, V3 imaging chip, Fast charging",
            "image_url": "https://example.com/vivox100pro.jpg",
            "description": "Camera-focused flagship with Zeiss partnership",
            "ois": True,
            "eis": True,
            "wireless_charging": True,
            "water_resistance": "IP68",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "iPhone 15",
            "brand": "Apple",
            "price": 79900,
            "display_size": 6.1,
            "display_resolution": "2556 x 1179",
            "processor": "A16 Bionic",
            "ram": 6,
            "storage": 128,
            "camera_main": "48MP + 12MP",
            "camera_front": "12MP",
            "battery_capacity": 3349,
            "charging_speed": "20W",
            "os": "iOS 17",
            "weight": 171,
            "dimensions": "147.6 x 71.6 x 7.80 mm",
            "colors": "Pink, Yellow, Green, Blue, Black",
            "features": "Face ID, MagSafe, USB-C, Dynamic Island",
            "image_url": "https://example.com/iphone15.jpg",
            "description": "Latest iPhone with USB-C and improved camera",
            "ois": True,
            "eis": True,
            "wireless_charging": True,
            "water_resistance": "IP68",
            "fingerprint_sensor": False,
            "face_unlock": True
        },
        {
            "name": "Samsung Galaxy S24",
            "brand": "Samsung",
            "price": 79999,
            "display_size": 6.2,
            "display_resolution": "2340 x 1080",
            "processor": "Snapdragon 8 Gen 3",
            "ram": 8,
            "storage": 256,
            "camera_main": "50MP + 10MP + 10MP",
            "camera_front": "12MP",
            "battery_capacity": 4000,
            "charging_speed": "25W",
            "os": "Android 14",
            "weight": 167,
            "dimensions": "147.0 x 70.6 x 7.6 mm",
            "colors": "Onyx Black, Marble Gray, Cobalt Violet, Amber Yellow",
            "features": "AI features, 7 years updates, Compact design",
            "image_url": "https://example.com/s24.jpg",
            "description": "Compact flagship with AI features and long-term support",
            "ois": True,
            "eis": True,
            "wireless_charging": True,
            "water_resistance": "IP68",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "Motorola Edge 50 Pro",
            "brand": "Motorola",
            "price": 31999,
            "display_size": 6.7,
            "display_resolution": "2712 x 1220",
            "processor": "Snapdragon 7 Gen 3",
            "ram": 12,
            "storage": 256,
            "camera_main": "50MP + 13MP + 10MP",
            "camera_front": "60MP",
            "battery_capacity": 4500,
            "charging_speed": "125W",
            "os": "Android 14",
            "weight": 186,
            "dimensions": "161.2 x 72.4 x 8.2 mm",
            "colors": "Luxury Lavender, Black Beauty",
            "features": "Stock Android, Fast charging, Premium design",
            "image_url": "https://example.com/edge50pro.jpg",
            "description": "Premium mid-range phone with stock Android experience",
            "ois": True,
            "eis": True,
            "wireless_charging": True,
            "water_resistance": "IP68",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "Redmi 12C",
            "brand": "Xiaomi",
            "price": 8999,
            "display_size": 6.71,
            "display_resolution": "1650 x 720",
            "processor": "MediaTek Helio G85",
            "ram": 4,
            "storage": 64,
            "camera_main": "50MP + 2MP",
            "camera_front": "5MP",
            "battery_capacity": 5000,
            "charging_speed": "10W",
            "os": "MIUI 13",
            "weight": 192,
            "dimensions": "168.76 x 76.41 x 8.77 mm",
            "colors": "Graphite Gray, Ocean Blue, Mint Green",
            "features": "Dual SIM, 4G, Fingerprint sensor",
            "image_url": "https://example.com/redmi12c.jpg",
            "description": "Budget-friendly phone with good battery life",
            "ois": False,
            "eis": True,
            "wireless_charging": False,
            "water_resistance": "IP52",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "Samsung Galaxy M14 5G",
            "brand": "Samsung",
            "price": 9999,
            "display_size": 6.6,
            "display_resolution": "2408 x 1080",
            "processor": "Exynos 1330",
            "ram": 4,
            "storage": 128,
            "camera_main": "50MP + 2MP + 2MP",
            "camera_front": "13MP",
            "battery_capacity": 6000,
            "charging_speed": "25W",
            "os": "Android 13",
            "weight": 206,
            "dimensions": "166.8 x 77.2 x 9.4 mm",
            "colors": "Icy Silver, Berry Blue",
            "features": "5G, Samsung Knox, 2 years updates",
            "image_url": "https://example.com/m14.jpg",
            "description": "5G phone with excellent battery life",
            "ois": False,
            "eis": True,
            "wireless_charging": False,
            "water_resistance": "IP67",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "Nothing Phone (2a)",
            "brand": "Nothing",
            "price": 23999,
            "display_size": 6.7,
            "display_resolution": "2412 x 1080",
            "processor": "MediaTek Dimensity 7200 Pro",
            "ram": 8,
            "storage": 128,
            "camera_main": "50MP + 50MP",
            "camera_front": "32MP",
            "battery_capacity": 5000,
            "charging_speed": "45W",
            "os": "Nothing OS 2.5",
            "weight": 190,
            "dimensions": "161.7 x 76.3 x 8.6 mm",
            "colors": "Black, White",
            "features": "Glyph Interface, Stock Android, Unique design",
            "image_url": "https://example.com/phone2a.jpg",
            "description": "Unique design phone with Glyph interface and stock Android",
            "ois": True,
            "eis": True,
            "wireless_charging": False,
            "water_resistance": "IP54",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        
        # Compact phones for one-hand use
        {
            "name": "iPhone 13 mini",
            "brand": "Apple",
            "price": 59900,
            "display_size": 5.4,
            "display_resolution": "2340 x 1080",
            "processor": "A15 Bionic",
            "ram": 4,
            "storage": 128,
            "camera_main": "12MP + 12MP",
            "camera_front": "12MP",
            "battery_capacity": 2406,
            "charging_speed": "20W",
            "os": "iOS 15",
            "weight": 141,
            "dimensions": "131.5 x 64.2 x 7.65 mm",
            "colors": "Pink, Blue, Midnight, Starlight, Red",
            "features": "Face ID, MagSafe, Ceramic Shield",
            "image_url": "https://example.com/iphone13mini.jpg",
            "description": "Compact iPhone with flagship features",
            "ois": True,
            "eis": True,
            "wireless_charging": True,
            "water_resistance": "IP68",
            "fingerprint_sensor": False,
            "face_unlock": True
        },
        {
            "name": "Samsung Galaxy S23",
            "brand": "Samsung",
            "price": 74999,
            "display_size": 6.1,
            "display_resolution": "2340 x 1080",
            "processor": "Snapdragon 8 Gen 2",
            "ram": 8,
            "storage": 128,
            "camera_main": "50MP + 10MP + 10MP",
            "camera_front": "12MP",
            "battery_capacity": 3900,
            "charging_speed": "25W",
            "os": "Android 13",
            "weight": 168,
            "dimensions": "146.3 x 70.9 x 7.6 mm",
            "colors": "Phantom Black, Cream, Green, Lavender",
            "features": "5G, Wireless charging, IP68",
            "image_url": "https://example.com/s23.jpg",
            "description": "Compact flagship with excellent camera",
            "ois": True,
            "eis": True,
            "wireless_charging": True,
            "water_resistance": "IP68",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        
        # Mid-range phones around 15k for battery king
        {
            "name": "Realme Narzo 70 Pro 5G",
            "brand": "Realme",
            "price": 15999,
            "display_size": 6.67,
            "display_resolution": "2400 x 1080",
            "processor": "MediaTek Dimensity 7050",
            "ram": 8,
            "storage": 128,
            "camera_main": "50MP + 2MP",
            "camera_front": "16MP",
            "battery_capacity": 5000,
            "charging_speed": "67W",
            "os": "Realme UI 4.0",
            "weight": 190,
            "dimensions": "162.9 x 75.1 x 8.1 mm",
            "colors": "Glass Green, Glass Gold",
            "features": "5G, Fast charging, Gaming mode",
            "image_url": "https://example.com/narzo70pro.jpg",
            "description": "Battery king with ultra-fast charging",
            "ois": False,
            "eis": True,
            "wireless_charging": False,
            "water_resistance": "IP54",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "Vivo T3x 5G",
            "brand": "Vivo",
            "price": 14999,
            "display_size": 6.72,
            "display_resolution": "2408 x 1080",
            "processor": "Snapdragon 6 Gen 1",
            "ram": 6,
            "storage": 128,
            "camera_main": "50MP + 2MP",
            "camera_front": "8MP",
            "battery_capacity": 6000,
            "charging_speed": "44W",
            "os": "Funtouch OS 14",
            "weight": 199,
            "dimensions": "165.7 x 76.0 x 9.0 mm",
            "colors": "Celestial Green, Crimson Bliss",
            "features": "5G, Fast charging, Large battery",
            "image_url": "https://example.com/t3x.jpg",
            "description": "Massive battery with fast charging",
            "ois": False,
            "eis": True,
            "wireless_charging": False,
            "water_resistance": "IP64",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        
        # Samsung phones under 25k
        {
            "name": "Samsung Galaxy A35 5G",
            "brand": "Samsung",
            "price": 22999,
            "display_size": 6.6,
            "display_resolution": "2340 x 1080",
            "processor": "Exynos 1380",
            "ram": 8,
            "storage": 128,
            "camera_main": "50MP + 8MP + 5MP",
            "camera_front": "13MP",
            "battery_capacity": 5000,
            "charging_speed": "25W",
            "os": "Android 14",
            "weight": 209,
            "dimensions": "161.7 x 78.0 x 8.2 mm",
            "colors": "Awesome Iceblue, Awesome Lilac, Awesome Navy",
            "features": "5G, Samsung Knox, 4 years updates",
            "image_url": "https://example.com/a35.jpg",
            "description": "Premium mid-range Samsung with 4 years updates",
            "ois": True,
            "eis": True,
            "wireless_charging": False,
            "water_resistance": "IP67",
            "fingerprint_sensor": True,
            "face_unlock": True
        },
        {
            "name": "Samsung Galaxy A25 5G",
            "brand": "Samsung",
            "price": 19999,
            "display_size": 6.5,
            "display_resolution": "2340 x 1080",
            "processor": "Exynos 1280",
            "ram": 6,
            "storage": 128,
            "camera_main": "50MP + 8MP + 2MP",
            "camera_front": "13MP",
            "battery_capacity": 5000,
            "charging_speed": "25W",
            "os": "Android 14",
            "weight": 197,
            "dimensions": "161.0 x 76.5 x 8.3 mm",
            "colors": "Awesome Blue, Awesome Yellow, Awesome Black",
            "features": "5G, Samsung Knox, 4 years updates",
            "image_url": "https://example.com/a25.jpg",
            "description": "Affordable Samsung with 5G and long-term support",
            "ois": True,
            "eis": True,
            "wireless_charging": False,
            "water_resistance": "IP67",
            "fingerprint_sensor": True,
            "face_unlock": True
        }
    ]
    
    try:
        # Clear existing data
        db.query(MobilePhone).delete()
        
        # Insert new data
        for phone_data in phones_data:
            phone = MobilePhone(**phone_data)
            db.add(phone)
        
        db.commit()
        print(f"Successfully seeded {len(phones_data)} mobile phones")
        
    except Exception as e:
        print(f"Error seeding database: {e}")
        db.rollback()
        raise
    finally:
        db.close()

if __name__ == "__main__":
    seed_database()
